version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - kube-orb/install-kubectl
      - kube-orb/install-kubeconfig
      - run: kubectl -n common get pod

orbs:
  kube-orb: circleci/kubernetes@0.11.0
